### ISSUE TITLE
Profile ResearchSubject to include DocumentReferences

### ISSUE THREAD

**Issue by bwalsh** [ncpi-fhir/ncpi-model-forge#30]
# Requester information
Please provide the following information:
- Name- Brian Walsh
- Affiliations- OHSU, AnVIL, GA4GH

# Request Details
Please provide the following information about what you wanting to accomplish with your model change request: 
- Purpose-  Capture repository information for files associated directly with Subject.
- Who it benefits- Researchers using the FHIR endpoint who wish to retrieve all resources associated with Subject
- Use case- See attached AnVIL snapshot, the GTEx study associates files directly with Subject

![image](https://user-images.githubusercontent.com/47808/95108027-8b5cd780-06ef-11eb-9b4c-b99045794ec2.png)

**Comment by torstees** [comment]
Assuming these are stored as DocumentReferences tied to Tasks which can be linked to a patient (either directly or through specimen), this isn't really necessary. There may be a need at some point in the future to flatten some things out for efficiency, but that will probably not be done via the actual fhir model.

**Comment by torstees** [comment]
These files should be linked to appropriate Sequencing tasks, which are linked to the subject by way of specimen.
