### ISSUE TITLE
Profile Specimen to include `DocumentReference`

### ISSUE THREAD

**Issue by bwalsh** [ncpi-fhir/ncpi-model-forge#31]
# Requester information
Please provide the following information:
- Name- Brian Walsh
- Affiliations- OHSU, AnVIL, GA4GH

# Request Details
Please provide the following information about what you wanting to accomplish with your model change request: 
- Purpose-  Capture repository information for files associated directly with Specimen.
- Who it benefits- Researchers using the FHIR endpoint who wish to retrieve all resources associated with Specimen
- Use case- See attached AnVIL snapshot, majority of studies have files associated directly with specimen.

https://github.com/anvilproject/client-apis/blob/pyAnVIL/pyAnVIL/notebooks/figures/AnVIL.png

**Comment by torstees** [comment]
If your objective is to tie CRAMs/BAMs/VCF/etc to a specimen, we recommend creating a Task for the sequencing task itself (which can link back to the specimen) and point the output of that task to the relevant DocumentReference entry.

**Comment by torstees** [comment]
We are currently linking Sequence data to Tasks (by way of Document References) and tasks to Specimen.
