### ISSUE TITLE
Profile Human Phenotype

### ISSUE THREAD

**Issue by torstees** [ncpi-fhir/ncpi-model-forge#34]
# Requester information
- Name-
Eric Torstenson

- Affiliations-
VUMC/Anvil

# Request Details
- Purpose-
Profiling these will permit us to clarify the purpose and the code system's that one can expect to be used. It also will clarify our usage of values and interpretation to indicate presence/absence of the specified phenotype. 

- Who it benefits-
Any group that captures information regarding the presence or absence of HPOs or other phenotypic traits. 

- Use case-
A patient may have one or more phenotypes that have been observed to be either present or absent. These can be annotated currently using Observations, but using a HumanPhenotype profile, there will be an added level of clarity as to what those entries represent.

**Comment by RobertJCarroll** [comment]
Fields:
- Code stores the phenotype code
- Value stores assertions about finding present or absent
- Interpretation also indicates the positive and negative

**Comment by RobertJCarroll** [comment]
We should investigate value sets and bindings for the `Value` and `Interpretation` fields.
